version: '3.8'

services:
  polyglot:
    image: ghcr.io/fxembed/polyglot:latest
    ports:
      - "3220:3220"
    environment:
      # Port configuration
      - PORT=3220
      
      # Optional: Azure AI Translator (uncomment and set if you have keys)
      # - AZURE_TRANSLATOR_KEY=your_azure_key
      # - AZURE_TRANSLATOR_REGION=eastus
      
      # Optional: DeepL Official API (uncomment and set if you have key)
      # - DEEPL_API_KEY=your_deepl_key
      
      # Optional: DeepLX Cloudflare Worker (uncomment and set if deployed)
      # - DEEPLX_CLOUDFLARE_URL=https://deeplx.example.workers.dev
      
             # Optional: AWS Translate (uncomment and set if you have keys)
       # - AWS_ACCESS_KEY_ID=your_access_key_id
       # - AWS_SECRET_ACCESS_KEY=your_access_key
       # - AWS_REGION=us-east-1
       
       # Optional: LibreTranslate (self-hosted or public instance)
       # - LIBRETRANSLATE_URL=https://libretranslate.com
       # - LIBRETRANSLATE_API_KEY=your_api_key_if_required
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3220/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s